name: ci-cd
on: [push]
env:
  BINARY_NAME: webmock

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello CI-CD"
      - name: check runtime versions
        run: |
          node -v
          npm -v