name: ci-cd
on: [push]
env:
  BINARY_NAME: webmock

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format Code
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
  unit-testing:
    runs-on: ubuntu-latest
    needs: [linting]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Run Unit Tests"
        run: go test ./...
      - name: "Get Repo Details"
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $BINARY_NAME